site_name: IHC - Grupo 8

repo_name: '2024.2-Grupo08'
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo08


nav:
  - Início: index.md


theme:
  name: material
  language: pt

  font:
    text: "Open Sans"
    code: "Source Code Pro"

  palette:
      primary: white

  features:
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest

  extra_css:
    - stylesheets/custom.css

  plugins:
    - search
    - typeset
    - nav-extensions

  markdown_extensions:
    - attr_list
    - md_in_html
    - tables
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true

