site_name: IHC - Grupo 8

repo_name: '2024.2-Grupo08'
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo08


nav:
  - Home: index.md
  - Apresentações:
    - Apresentação 1: apresent/01.md 
  - Atas:
    - Ata 01: atas/01.md
    - Ata 02: atas/02.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Metodologias: planejamento/metodologia.md
    - Ferramentas: planejamento/ferramentas.md
    - Sites Avaliadaos: planejamento/sitesAvaliados.md
    - Site Escolhido: planejamento/siteEscolhido.md
    - Processo de Design: planejamento/processoDesign.md
  - Verificação:
      - Verificação do Grupo:
          - Etapa 1:
              - Planejamento da Verificação da Etapa 1: verificacao/grupo/etapa1/planejamento-verificacao-etapa1.md
              - Cronograma: verificacao/grupo/etapa1/verificacao-cronograma.md
              - Ferramentas: verificacao/grupo/etapa1/verificacao-ferramentas.md
              - Processo de Design: verificacao/grupo/etapa1/verificacao-processo-design.md
              - Site Escolhido: verificacao/grupo/etapa1/verificacao-site-escolhido.md



theme:
  name: material
  language: pt

  font:
    text: "Open Sans"
    code: "Source Code Pro"

  icon:
    admonition:
      <type>: material/alert-circle

  palette:
      primary: white

  features:
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    - navigation.tracking

  extra_css:
    - stylesheets/custom.css

  plugins:
    - search
    - typeset
    - nav-extensions
    - glightbox

  markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

